export const BestSellerData = [
  {
    id: 1,
    name: "Premium Sneakers",
    description: "Comfortable and stylish everyday sneakers",
    price: 149.99,
    category: "shoe",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 2,
    name: "Running Shoes",
    description: "High-performance running shoes for long-distance",
    price: 199.99,
    category: "shoe",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 3,
    name: "Casual Loafers",
    description: "Stylish loafers for everyday wear",
    price: 129.99,
    category: "shoe",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 4,
    name: "Leather Boots",
    description: "Durable and fashionable leather boots",
    price: 249.99,
    category: "shoe",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 5,
    name: "Sporty Sandals",
    description: "Breathable and lightweight sandals",
    price: 89.99,
    category: "shoe",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
];
