export const productData = [
  // Shoes (1-5)
  {
    id: 1,
    name: "Premium Sneakers",
    description: "Comfortable and stylish everyday sneakers",
    price: 149.99,
    category: "shoe",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 2,
    name: "Running Shoes",
    description: "High-performance running shoes for long-distance",
    price: 199.99,
    category: "shoe",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 3,
    name: "Casual Loafers",
    description: "Stylish loafers for everyday wear",
    price: 129.99,
    category: "shoe",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 4,
    name: "Leather Boots",
    description: "Durable and fashionable leather boots",
    price: 249.99,
    category: "shoe",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 5,
    name: "Sporty Sandals",
    description: "Breathable and lightweight sandals",
    price: 89.99,
    category: "shoe",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },

  // Bags (6-10)
  {
    id: 6,
    name: "Leather Handbag",
    description: "Elegant and spacious leather handbag",
    price: 299.99,
    category: "bag",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 7,
    name: "Travel Backpack",
    description: "Water-resistant backpack for travel",
    price: 189.99,
    category: "bag",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 8,
    name: "Tote Bag",
    description: "Large tote bag with multiple compartments",
    price: 109.99,
    category: "bag",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 9,
    name: "Crossbody Bag",
    description: "Compact crossbody bag for everyday essentials",
    price: 139.99,
    category: "bag",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 10,
    name: "Gym Duffel Bag",
    description: "Spacious and durable gym bag",
    price: 159.99,
    category: "bag",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },

  // Slippers (11-15)
  {
    id: 11,
    name: "Comfort Slippers",
    description: "Soft and cushioned slippers for indoor wear",
    price: 59.99,
    category: "slipper",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 12,
    name: "Outdoor Slippers",
    description: "Durable slippers for outdoor use",
    price: 69.99,
    category: "slipper",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 13,
    name: "Memory Foam Slippers",
    description: "Plush slippers with memory foam insole",
    price: 79.99,
    category: "slipper",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 14,
    name: "Flip-Flop Sandals",
    description: "Easy slip-on flip-flops for casual wear",
    price: 39.99,
    category: "slipper",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 15,
    name: "Luxury Slippers",
    description: "High-end slippers with leather finish",
    price: 99.99,
    category: "slipper",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },

  // Heels (16-20)
  {
    id: 16,
    name: "Classic High Heels",
    description: "Timeless high heels for formal occasions",
    price: 179.99,
    category: "heel",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 17,
    name: "Platform Heels",
    description: "Comfortable platform heels for extra height",
    price: 199.99,
    category: "heel",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 18,
    name: "Strappy Heels",
    description: "Elegant strappy heels for evening wear",
    price: 149.99,
    category: "heel",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 19,
    name: "Peep Toe Heels",
    description: "Trendy peep-toe heels for casual and formal",
    price: 169.99,
    category: "heel",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 20,
    name: "Stiletto Heels",
    description: "Chic stiletto heels for a bold look",
    price: 189.99,
    category: "heel",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },

  // Accessories (21-25)
  {
    id: 21,
    name: "Leather Wallet",
    description: "Compact leather wallet with card slots",
    price: 59.99,
    category: "accessory",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 22,
    name: "Sunglasses",
    description: "Stylish polarized sunglasses",
    price: 79.99,
    category: "accessory",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 23,
    name: "Wristwatch",
    description: "Elegant wristwatch with leather strap",
    price: 149.99,
    category: "accessory",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 24,
    name: "Necklace",
    description: "Gold-plated necklace with minimalist design",
    price: 199.99,
    category: "accessory",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
  {
    id: 25,
    name: "Leather Belt",
    description: "High-quality leather belt with metal buckle",
    price: 89.99,
    category: "accessory",
    image: "https://i.postimg.cc/jjBShzp6/1000-X-1000.png",
  },
];
